The `/me` endpoint is marked as deprecated
transferwise/public-api-postman-collection pull request #1
Opened 2018-12-20 13:57 UTC by theSKa

The `/me` endpoint is marked as deprecated in our API.
Since this is the case we need to stop advertising it externally.

2018-12-20 14:03 UTC, JamesFerretti commented
It is in use by both bunq and monzo, why has it been deprecated? I will check the use case now and see if we can recommend another solution, if so we can remove from docs.

2018-12-20 14:06 UTC, JamesFerretti commented
The use case is to check the email of the user when the account is linked to make sure it was the user they _expected_ to link to. In the case of a shared device another user could already be logged in to TW at the point of the OAuth redirect, we we don't check this we could end up linking a user's bank account to the wrong TW account. There is currently no other way to get this info that I know of other than `GET /v1/users/{userId}` which doesn't work as the bank doesn't know the ID of the user based solely on the token.

2018-12-20 14:07 UTC, JamesFerretti requested changes
See offline discussion, I think this should be in the public API until we have another solution.

2018-12-20 14:44 UTC, theSKa commented
@JamesFerretti 
I am thinking we need not to increase the number of clients using the `/me` endpoint.
We did not delete the endpoint from gateway, just that it is marked as deprecated for a while now.
What would make sense would be to allow client credentials to check tokens.

Can we just remove the me endpoint in the postman and let Bunq and monzo use a tagged version of this repo?

2019-06-17 14:06 UTC, JamesFerretti approved these changes

2019-06-17 14:06 UTC, merged